#consumer key
CONSUMER_KEY: XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
CONSUMER_SECRET: XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

#access token
ACCESS_TOKEN: XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
ACCESS_SERCRET: XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

